### ISSUE TITLE
What's the meaning of "n_list"?

### ISSUE THREAD

**Issue by Chunngai** [nusnlp/geccl#1]
Hello. 

Thank you for releasing the code of the paper. 

I have a question about the variable `n_list` found in `label_smoothed_cross_entropy.py` and `new_max_margin_loss.py` of GEC-PD (`gec-pseudo`).

It seems that each elem `e_i` in `n_list` means only the first `e_i` of the neg targets are used for the loss calculation. But what's its purpose?

**Comment by MichaelCaohn** [comment]
May I know which line in label_smoothed_cross_entropy.py are you referring to? I haven't found n_list variable in label_smoothed_cross_entropy.py.

For the n_list variable used in new_max_margin_loss.py: we use this variable to store the number of the negative targets for each source sentence, which corresponds to the variable N_{i} in Eq. 4 of our paper.

**Comment by Chunngai** [comment]
Oh sorry. I originally wanted to say `multi_target_pair_dataset.py` but not `label_smoothed_cross_entropy.py`. 

I understand the meaning of `n_list` now. Thank you!
