### ISSUE TITLE
关于中文语法纠错

### ISSUE THREAD

**Issue by Windysum** [nusnlp/geccl#3]
作者你好，请问一下该模型是否可用于中文语法纠错

**Comment by MichaelCaohn** [comment]
Hi, Thanks for your interest in our work. 

For others to benefit from this issue, I will answer it in English. 

Q: If the model/method can be used in the Chinese GEC:

This model is based on the English BART model, so you cannot directly use it in Chinese GEC. To use in Chinese GEC, you may consider changing the following two things:

1. Change the pretained language model to its Chinese version. 
2. I have hard-coded the encoding value for 1, 2, 3, 4, and 5 here[https://github.com/nusnlp/geccl/blob/main/BART-GEC/fairseq/data/multi_target_pair_dataset.py#L71], the values listed here only suitable for English BART model, you also need to modify this part.

For the rest of the code, I think you can use it directly. However, we have not tested if it works well in the Chinese GEC task.
